//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWMS_LocationServer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IWMS_LocationServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 基站SN 的本地化字符串。
        /// </summary>
        public static string IDS_ANCHOR_SN {
            get {
                return ResourceManager.GetString("IDS_ANCHOR_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平翻转 的本地化字符串。
        /// </summary>
        public static string IDS_H_TURN {
            get {
                return ResourceManager.GetString("IDS_H_TURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平偏移（X轴） 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_H_OFFSET {
            get {
                return ResourceManager.GetString("IDS_LABEL_H_OFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平缩放（X轴） 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_H_SCALE {
            get {
                return ResourceManager.GetString("IDS_LABEL_H_SCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 scene_id 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_SCENEID {
            get {
                return ResourceManager.GetString("IDS_LABEL_SCENEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直偏移（Y轴） 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_V_OFFSET {
            get {
                return ResourceManager.GetString("IDS_LABEL_V_OFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直缩放（Y轴） 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_V_SCALE {
            get {
                return ResourceManager.GetString("IDS_LABEL_V_SCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X(m) 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_X {
            get {
                return ResourceManager.GetString("IDS_LABEL_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y(m) 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_Y {
            get {
                return ResourceManager.GetString("IDS_LABEL_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z(m) 的本地化字符串。
        /// </summary>
        public static string IDS_LABEL_Z {
            get {
                return ResourceManager.GetString("IDS_LABEL_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图 的本地化字符串。
        /// </summary>
        public static string IDS_MAP {
            get {
                return ResourceManager.GetString("IDS_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        public static string IDS_PERCENT {
            get {
                return ResourceManager.GetString("IDS_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pixels 的本地化字符串。
        /// </summary>
        public static string IDS_PIXELS {
            get {
                return ResourceManager.GetString("IDS_PIXELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置原点 的本地化字符串。
        /// </summary>
        public static string IDS_SET_ORIGIN {
            get {
                return ResourceManager.GetString("IDS_SET_ORIGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示原点 的本地化字符串。
        /// </summary>
        public static string IDS_SHOW_ORIGIN {
            get {
                return ResourceManager.GetString("IDS_SHOW_ORIGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签SN 的本地化字符串。
        /// </summary>
        public static string IDS_TAG_SN {
            get {
                return ResourceManager.GetString("IDS_TAG_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直翻转 的本地化字符串。
        /// </summary>
        public static string IDS_V_TURN {
            get {
                return ResourceManager.GetString("IDS_V_TURN", resourceCulture);
            }
        }
    }
}
